### ISSUE TITLE
是否有ubuntu18.04一键安装的需求？

### ISSUE THREAD

**Issue by stdnt-xiao** [wubolive/dss-linkis-ansible#11]
我准备基于ubuntu18.04开发一个自动安装版本，如果有需要我可以贡献一个分支。

**Comment by wubolive** [comment]
> 我准备基于ubuntu18.04开发一个自动安装版，如果有需要我可以贡献一个支持。

DSS官方文档都表示只支持CentOS为6或者7，可以先验证一下Ubuntu系统手动部署是否可行

**Comment by stdnt-xiao** [comment]
好的👌，我先测试看一下

**Comment by stdnt-xiao** [comment]
@wubolive 
我这边主要是想解决信创的问题，目前采用的ubuntu部署ambari+hdp。
昨天我基于openeuler22.03使用[dss-linkis-ansible](https://github.com/wubolive/dss-linkis-ansible)做一些软件源的修改，是可以正常运行起来linkis+dss的。
目前我这边有一个openeuler22.03的部署版本，是否考虑创建一个openeuler22.03的分支？
