### ISSUE TITLE
部署dss成功，新建工作流出现警告

### ISSUE THREAD

**Issue by stdnt-xiao** [wubolive/dss-linkis-ansible#4]
部署在阿里云ECS

Warning code(警告码): 50032, Warning message(警告信息): Try to ask Linkis for creating a new contextId failed(向Linkis请求创建一个ContextID失败)! Linkis error msg: HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/contextservice/createContextID request failed! ResponseBody is {"method":"/api/rest_j/v1/contextservice/createContextID","status":1,"message":"IllegalArgumentException: Supplied VIP Address cannot be null","data":{"data":null}}. errCode: 10905 ,desc: URL /api/rest_j/v1/contextservice/createContextID request failed! ResponseBody is {"method":"/api/rest_j/v1/contextservice/createContextID","status":1,"message":"IllegalArgumentException: Supplied VIP Address cannot be null","data":{"data":null}}. ,ip: dss-service ,port: 9003 ,serviceKind: dss-framework-orchestrator-server-dev ,ip: dss-service ,port: 9003 ,serviceKind: dss-framework-orchestrator-server-dev.

**Comment by wubolive** [comment]
> Try to ask Linkis for creating a new contextId failed(向Linkis请求创建一个ContextID失败)!

使用问题请查看官方文档：https://docs.qq.com/doc/DSGZhdnpMV3lTUUxq 或向社区提问

**Comment by XXwhite** [comment]
我也遇到了这个问题  ， 解决了没 ，我官方文档没有给出具体解决办法

**Comment by stdnt-xiao** [comment]
> 我也遇到了这个问题 ， 解决了没 ，我官方文档没有给出具体解决办法

没有解决，后面没有测试了，建议使用这个项目最新版本进行部署

**Comment by XXwhite** [comment]
> 

我把linkis的版本换成了1.3.1，这个错误就消失了

**Comment by seawindh** [comment]
> > 
> 
> 我把linkis的版本换成了1.3.1，这个错误就消失了

请问升级后会影响其他组件吗？有可以参考的升级文档吗？ 谢谢。

**Comment by XXwhite** [comment]
> > > 
> > 
> > 
> > 我把linkis的版本换成了1.3.1，这个错误就消失了
> 
> 请问升级后会影响其他组件吗？有可以参考的升级文档吗？ 谢谢。

暂时没发现有影响 升级的话 就是将作者脚本中的linkis下载的版本换成1.3.1，其他都一样，下载地址需要用到官网的。

**Comment by stdnt-xiao** [comment]
我的问题应是内容不够没有起来，后来增大了内存是可以运行的。目前采用的服务器配置是4核32G
