### ISSUE TITLE
安装streamis有个ignoring 不知道会不会影响

### ISSUE THREAD

**Issue by linkagt** [wubolive/dss-linkis-ansible#7]
TASK [streamis : 启动服务] ********************************************************************************************************************************************************************************************************************************
fatal: [dss-service]: FAILED! => {"changed": true, "cmd": "source /etc/profile ~/.bashrc ; sh bin/start-streamis-server.sh", "delta": "0:00:02.040335", "end": "2023-01-06 00:15:24.059053", "msg": "non-zero return code", "rc": 1, "start": "2023-01-06 00:15:22.018718", "stderr": "", "stderr_lines": [], "stdout": "Streamis Server start succeeded!\nJava HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=500m; support was removed in 8.0", "stdout_lines": ["Streamis Server start succeeded!", "Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=500m; support was removed in 8.0"]}
...ignoring

**Comment by stdnt-xiao** [comment]
存在相同的issue[#3](https://github.com/wubolive/dss-linkis-ansible/issues/3),关闭掉这一个

**Comment by stdnt-xiao** [comment]
存在相同的issuehttps://github.com/wubolive/dss-linkis-ansible/issues/3,关闭掉这一个
